version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./files:/app/files"
      - "./archive:/app/archive:ro"
    env_file:
      - prod-web.env
    environment:
      DB_ENGINE: pg
      DB_PG_HOST: postgres
      DB_PG_USERNAME: pguser
      DB_PG_PASSWORD: pguser
  postgres:
    image: "postgres:14"
    volumes:
      - "./postgresql:/var/lib/postgresql"
      - "./postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: scpwiki
